version: '3.8'

services:
  vinyl-vault:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vinyl-vault-app
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - GOOGLE_CLOUD_PROJECT=universal-trail-492014-n5
      - GOOGLE_CLOUD_LOCATION=global
      - FIRESTORE_DATABASE_ID=vinylvault-hk
      - GCS_BUCKET_NAME=universal-trail-492014-n5-vinyl-vault-hk-data
      - GOOGLE_APPLICATION_CREDENTIALS=/app/adc.json
    volumes:
      - ~/.config/gcloud/application_default_credentials.json:/app/adc.json:ro
      - .:/app
    restart: unless-stopped
